export default () => [
  <link
    key="0"
    rel="apple-touch-icon"
    sizes="57x57"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="1"
    rel="apple-touch-icon"
    sizes="60x60"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="2"
    rel="apple-touch-icon"
    sizes="72x72"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="3"
    rel="apple-touch-icon"
    sizes="76x76"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="4"
    rel="apple-touch-icon"
    sizes="114x114"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="15"
    rel="apple-touch-icon"
    sizes="120x120"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="5"
    rel="apple-touch-icon"
    sizes="144x144"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="6"
    rel="apple-touch-icon"
    sizes="152x152"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="7"
    rel="apple-touch-icon"
    sizes="180x180"
    href="http://localhost:3000/favicon/apple-touch-icon.png"
  />,
  <link
    key="8"
    rel="icon"
    type="image/png"
    sizes="192x192"
    href="http://localhost:3000/favicon/android-chrome-192x192.png"
  />,
  <link
    key="9"
    rel="icon"
    type="image/png"
    sizes="32x32"
    href="http://localhost:3000/favicon/favicon.ico"
  />,
  <link
    key="10"
    rel="icon"
    type="image/png"
    sizes="96x96"
    href="http://localhost:3000/favicon/mstile-144x144.png"
  />,
  <link
    key="11"
    rel="icon"
    type="image/png"
    sizes="16x16"
    href="http://localhost:3000/favicon/favicon-16x16.png"
  />,
  <meta key="12" name="msapplication-TileColor" content="#ffffff" />,
  <meta
    key="13"
    name="msapplication-TileImage"
    content="http://localhost:3000/favicon/mstile-144x144.png"
  />,
  <meta key="14" name="theme-color" content="#ffffff" />
];
